- name: Manage multipathd
  hosts: all
  become: true
  tasks:
    - name: Ensure multipathd is stopped and disabled
      ansible.builtin.systemd_service:
        name: multipathd
        state: stopped
        enabled: false

    - name: Ensure multipathd.socket is stopped and disabled
      ansible.builtin.systemd_service:
        name: multipathd.socket
        state: stopped
        enabled: false